= Custom modifications
* Originally, the exact same jar (up to the identical version) is extracted every time it is included as a dependency. For instance, my-jar-1-0.jar would be extracted 3 times to my-jar-1-0.jar, my-jar-1-0.jar.1, my-jar-1-0.jar.2. For analyzing a large amount of applications, we only need a single extracted version for optimalization purposes. This has been added in this fork.
* Originally, even if -keepWorkDirs would be specified to keep extracted archives on disk, on consecutive runs it would simply extract these archives again and overwrite them. In this fork, if an archive has already been extracted, it will not extract it again, and use the extracted folder for optimalization purposes.
* Originally, individual .class files would be decompiled again and again, even if they have already been decompiled. This fork optimizes this, such that it does not decompile the same .class file multiple times (this is different from extracting archives!).
* Lazy report generation, if a report has already been generated, do not generate the same report again.
* Retry until succeed: If windup fails for some reason and crashes, it will retry until it succeeds or an administrator solves the issue.
* Added bash script for batch processing due to RAM constraints for high amount of applications. After generating individual reports, the CSVs are merged.

= Original Readme
== Windup
Windup is an automated application migration and assessment tool.
If you want to contribute or participate in developer discussions,
join us on the `irc.freenode.net` `#windup` channel
or subscribe to the link:https://lists.jboss.org/mailman/listinfo/windup-dev[windup-dev mailing list].

== Get involved

* Windup Wiki: https://github.com/windup/windup/wiki
  ** Windup documentation is on the wiki:
    https://github.com/windup/windup/wiki/User-Guide[User Guide],
    https://github.com/windup/windup/wiki/Rules-Development-Guide[Rules Development Guide],
    https://github.com/windup/windup/wiki/Core-Development-Guide[Core Development Guide]
* Forums: https://developer.jboss.org/en/windup
* Issue Tracker: https://issues.jboss.org/browse/WINDUP
* Users Mailing List: windup-users@lists.jboss.org
* Developers Mailing List: windup-dev@lists.jboss.org
* Commits Mailing List: windup-commits@lists.jboss.org


=== Installation and Usage

You may download the link:http://windup.jboss.org/download.html[latest Windup release].
After that, follow the link:https://github.com/windup/windup/wiki/Execute[User Guide, Execute Windup].

Windup distribution contains a sample file to try Windup with. Try the following command in a console:

    bin/windup --target eap --input samples/jee-example-app-1.0.0.ear

This will create a report next to the scanned archive:

    samples/jee-example-app-1.0.0.ear.report/index.html


=== Project Source Code Format

This project has an agreed upon source format style documented via an
link:https://github.com/windup/windup/blob/master/ide-config/Eclipse_Code_Format_Profile.xml[Eclipse code formatter profile].
If using an alternate IDE, plugins are available to allow use of this profile (see below).
All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

